# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180710_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 10, 11, 57, 21, 100408)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(default='', upload_to='blog/%Y/%m', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(default='', upload_to='blog/%Y/%m', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(default='', upload_to='blog/%Y/%m', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 10, 11, 57, 21, 101505)),
        ),
    ]
