# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 06:31
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180710_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=400, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 12, 14, 31, 13, 765103)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 12, 14, 31, 13, 773557)),
        ),
    ]
