# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180712_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 12, 19, 0, 19, 589834)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article', verbose_name='文章编号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 12, 19, 0, 19, 591873)),
        ),
    ]
