# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 05:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=100, verbose_name='城市')),
                ('district', models.CharField(default='', max_length=100, verbose_name='区域')),
                ('address', models.CharField(default='', max_length=100, verbose_name='详细地址')),
                ('order_name', models.CharField(default='', max_length=20, verbose_name='下单人姓名')),
                ('order_mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 9, 29, 13, 18, 25, 367114), verbose_name='添加时间')),
                ('usera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.CreateModel(
            name='UserAli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, help_text='支付宝昵称', max_length=30, null=True, verbose_name='支付宝昵称')),
                ('avatar', models.CharField(blank=True, help_text='用户头像地址', max_length=300, null=True, verbose_name='用户头像地址')),
                ('userali_id', models.CharField(blank=True, help_text='支付宝id', max_length=50, null=True, verbose_name='支付宝id')),
                ('usera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户支付宝',
                'verbose_name_plural': '用户支付宝',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问')], default=1, help_text='留言类型：(1)留言,(2)投诉,(3)询问', verbose_name='消息类型')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='主题')),
                ('message', models.TextField(default='', help_text='留言内容', verbose_name='留言内容')),
                ('file', models.FileField(default='', help_text='上传文件', upload_to='message/', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 9, 29, 13, 18, 25, 368750), verbose_name='添加时间')),
                ('userlm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
            },
        ),
    ]
