# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 06:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0003_auto_20180929_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayOrderSettle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='订单id')),
                ('out_request_no', models.CharField(blank=True, help_text='结算流水号', max_length=100, null=True, verbose_name='结算流水号')),
                ('trans_out', models.CharField(blank=True, max_length=100, null=True, verbose_name='支出方用户号')),
                ('trans_in', models.CharField(blank=True, max_length=100, null=True, verbose_name='收入方用户号')),
                ('amount', models.FloatField(default=0, help_text='支付金额', verbose_name='支付金额')),
                ('useraos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='结算用户')),
            ],
            options={
                'verbose_name': '支付宝结算',
                'verbose_name_plural': '支付宝结算',
            },
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 14, 12, 43, 339064), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='order_name',
            field=models.CharField(default='', max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 14, 12, 43, 339722), verbose_name='添加时间'),
        ),
    ]
