# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20180929_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipayordersettle',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 16, 34, 9, 151729), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 16, 34, 9, 153146), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 16, 34, 9, 154484), verbose_name='添加时间'),
        ),
    ]
