# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_auto_20181001_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipayordersettle',
            name='trade_no',
            field=models.CharField(blank=True, help_text='支付宝交易号', max_length=50, null=True, verbose_name='支付宝交易号'),
        ),
        migrations.AlterField(
            model_name='alipayordersettle',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 17, 11, 42, 276206), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 17, 11, 42, 277150), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 17, 11, 42, 277933), verbose_name='添加时间'),
        ),
    ]
