# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0009_auto_20181001_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alipayordersettle',
            old_name='trade_no',
            new_name='alipay_trade_no',
        ),
        migrations.AlterField(
            model_name='alipayordersettle',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 17, 27, 6, 624360), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 17, 27, 6, 625407), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 17, 27, 6, 626306), verbose_name='添加时间'),
        ),
    ]
