# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0012_auto_20181004_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='order_mobile',
            new_name='user_mobile',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='order_name',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='alipayordersettle',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 7, 55, 565861), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 7, 55, 566595), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 7, 55, 567202), verbose_name='添加时间'),
        ),
    ]
