# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0014_auto_20181004_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayordersettle',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 18, 25, 287656), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 18, 25, 288396), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 18, 25, 289056), verbose_name='添加时间'),
        ),
    ]
