# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0016_auto_20181005_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayordersettle',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 2, 4, 37, 756215, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 2, 4, 37, 756976, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 2, 4, 37, 757612, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
