# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 05:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_operation', '0003_auto_20180929_1342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='订单名称', max_length=30, null=True, verbose_name='订单名称')),
                ('order_sn', models.CharField(blank=True, help_text='订单编号', max_length=50, null=True, verbose_name='订单编号')),
                ('order_type', models.IntegerField(blank=True, choices=[(2, '快递类'), (3, '送东西类'), (1, '带饭类')], default=1, help_text='(1)带饭类,(2)快递类,(3)送东西类', null=True, verbose_name='订单类型')),
                ('order_emergency', models.IntegerField(blank=True, choices=[(2, '着急'), (3, '一般'), (1, '非常着急')], default=3, help_text='(1)非常着急,(2)着急,(3)一般', null=True, verbose_name='订单紧急程度')),
                ('order_decs', models.TextField(default='', help_text='备注', verbose_name='备注')),
                ('order_total', models.FloatField(default=0, help_text='订单总金额', verbose_name='订单总金额')),
                ('purchase', models.FloatField(default=0, help_text='第三方购买费', verbose_name='第三方购买费')),
                ('tax', models.FloatField(default=0, help_text='手续费', verbose_name='手续费')),
                ('run_money', models.FloatField(default=0, help_text='跑腿费', verbose_name='跑腿费')),
                ('order_status', models.IntegerField(blank=True, choices=[(1, '完成'), (3, '取消'), (2, '未完成'), (4, '创建')], default=4, help_text='(1)完成,(2)未完成,(3)取消,(4)创建', null=True, verbose_name='订单状态')),
                ('order_pay_status', models.CharField(choices=[('TRADE_FINISHED', '交易完成'), ('TRADE_SUCCESS', '支付成功'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '交易关闭')], default='WAIT_BUYER_PAY', help_text='订单支付状态', max_length=30, verbose_name='订单支付状态')),
                ('is_accept', models.BooleanField(default=False, help_text='是否已接单', verbose_name='是否已接单')),
                ('distance', models.FloatField(default=0, help_text='路程', verbose_name='路程')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 9, 29, 13, 42, 11, 295217), help_text='添加时间', verbose_name='添加时间')),
                ('send_user_id', models.IntegerField(blank=True, help_text='下单人id', null=True, verbose_name='下单人id')),
                ('send_address', models.CharField(blank=True, default='', help_text='下单人地址', max_length=100, null=True, verbose_name='下单地址')),
                ('send_name', models.CharField(blank=True, default='', help_text='下单人姓名', max_length=20, null=True, verbose_name='下单人姓名')),
                ('send_mobile', models.CharField(blank=True, help_text='下单人联系电话', max_length=11, null=True, verbose_name='下单人联系电话')),
                ('accept_user_id', models.IntegerField(blank=True, help_text='接单人id', null=True, verbose_name='接单人id')),
                ('accept_address', models.CharField(blank=True, default='', help_text='接单人地址', max_length=100, null=True, verbose_name='接单地址')),
                ('accept_name', models.CharField(blank=True, default='', help_text='接单人姓名', max_length=20, null=True, verbose_name='接单人姓名')),
                ('accept_mobile', models.CharField(blank=True, help_text='接单人联系电话', max_length=11, null=True, verbose_name='接单人联系电话')),
                ('currentuser', models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_user', related_query_name='orders_order_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressac', models.ForeignKey(help_text='地址信息', on_delete=django.db.models.deletion.CASCADE, related_name='accept_address', to='user_operation.UserAddress', verbose_name='地址信息')),
                ('orderac', models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, related_name='orders_orderaccept_order', related_query_name='orders_orderaccept_order', to='orders.Order', verbose_name='订单')),
                ('useroac', models.ForeignKey(help_text='接单人', on_delete=django.db.models.deletion.CASCADE, related_name='orders_orderaccept_user', related_query_name='orders_orderaccept_user', to=settings.AUTH_USER_MODEL, verbose_name='接单人')),
            ],
            options={
                'verbose_name': '接订单',
                'verbose_name_plural': '接订单',
            },
        ),
    ]
