# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 06:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180929_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 14, 15, 12, 654915), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_emergency',
            field=models.IntegerField(blank=True, choices=[(2, '着急'), (3, '一般'), (1, '非常着急')], default=3, help_text='(1)非常着急,(2)着急,(3)一般', null=True, verbose_name='订单紧急程度'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(3, '取消'), (1, '完成'), (4, '创建'), (2, '未完成')], default=4, help_text='(1)完成,(2)未完成,(3)取消,(4)创建', null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(blank=True, choices=[(1, '带饭类'), (2, '快递类'), (3, '送东西类')], default=1, help_text='(1)带饭类,(2)快递类,(3)送东西类', null=True, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='orderaccept',
            name='addressac',
            field=models.ForeignKey(help_text='地址信息', on_delete=django.db.models.deletion.CASCADE, to='user_operation.UserAddress', verbose_name='地址信息'),
        ),
        migrations.AlterField(
            model_name='orderaccept',
            name='orderac',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='orderaccept',
            name='useroac',
            field=models.ForeignKey(help_text='接单人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接单人'),
        ),
    ]
