# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0022_auto_20181005_1856'),
        ('orders', '0019_auto_20181005_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currentaddress',
            field=models.ForeignKey(blank=True, help_text='地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_operation.UserAddress', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 18, 56, 21, 772011), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_emergency',
            field=models.IntegerField(blank=True, choices=[(3, '一般'), (1, '非常着急'), (2, '着急')], default=3, help_text='(1)非常着急,(2)着急,(3)一般', null=True, verbose_name='订单紧急程度'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(4, '创建'), (3, '取消'), (1, '完成'), (2, '未完成')], default=4, help_text='(1)完成,(2)未完成,(3)取消,(4)创建', null=True, verbose_name='订单状态'),
        ),
    ]
