# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20181006_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaccept',
            name='tools',
            field=models.CharField(blank=True, choices=[('walking', '步行'), ('transit', '公交'), ('driving', '驾车')], default='walking', help_text='出行方式', max_length=20, null=True, verbose_name='出行方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 13, 5, 8, 679806), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_emergency',
            field=models.IntegerField(blank=True, choices=[(2, '着急'), (3, '一般'), (1, '非常着急')], default=3, help_text='(1)非常着急,(2)着急,(3)一般', null=True, verbose_name='订单紧急程度'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(2, '未完成'), (1, '完成'), (4, '创建'), (3, '取消')], default=4, help_text='(1)完成,(2)未完成,(3)取消,(4)创建', null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(blank=True, choices=[(2, '快递类'), (1, '带饭类'), (3, '送东西类')], default=1, help_text='(1)带饭类,(2)快递类,(3)送东西类', null=True, verbose_name='订单类型'),
        ),
    ]
