# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookhouse',
            fields=[
                ('house_id', models.AutoField(db_column='House_ID', primary_key=True, serialize=False)),
                ('house_name', models.CharField(db_column='House_Name', max_length=50)),
            ],
            options={
                'db_table': 'bookhouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('book_id', models.IntegerField(db_column='Book_ID', primary_key=True, serialize=False)),
                ('book_name', models.CharField(db_column='Book_Name', max_length=60)),
                ('book_author', models.CharField(db_column='Book_Author', max_length=60)),
                ('book_price', models.FloatField(db_column='Book_Price')),
                ('book_house', models.CharField(db_column='Book_House', max_length=50)),
                ('book_number', models.IntegerField(db_column='Book_Number')),
                ('book_type', models.CharField(db_column='Book_Type', max_length=50)),
                ('image', models.ImageField(upload_to='courses/%Y/%m')),
            ],
            options={
                'db_table': 'bookinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('type_id', models.AutoField(db_column='Type_ID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='Type_Name', max_length=50)),
            ],
            options={
                'db_table': 'booktype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(db_column='User_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_Name', max_length=50)),
                ('user_password', models.CharField(db_column='User_Password', max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
