# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imau', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookhouse',
            options={'managed': False, 'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.AlterModelTable(
            name='bookhouse',
            table='BookHouse',
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='BookInfo',
        ),
        migrations.AlterModelTable(
            name='booktype',
            table='BookType',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
