# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imau', '0004_article_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
