# Generated by Django 2.1 on 2018-08-29 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 19, 51, 26, 360001), verbose_name='添加时间'),
        ),
    ]
