# Generated by Django 2.1 on 2018-08-31 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180831_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 13, 10, 16, 93486), verbose_name='添加时间'),
        ),
    ]
