# Generated by Django 2.1 on 2018-08-31 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180831_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 20, 12, 1, 335817), verbose_name='添加时间'),
        ),
    ]
