# Generated by Django 2.1 on 2018-08-31 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180831_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 21, 26, 26, 624027), verbose_name='添加时间'),
        ),
    ]
