# Generated by Django 2.1 on 2018-09-01 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180831_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 11, 5, 45, 827129), verbose_name='添加时间'),
        ),
    ]
