# Generated by Django 2.1 on 2018-09-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180901_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 15, 26, 2, 745614), verbose_name='添加时间'),
        ),
    ]
