# Generated by Django 2.1 on 2018-09-02 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180901_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 17, 3, 29, 878861), verbose_name='添加时间'),
        ),
    ]
