# Generated by Django 2.1 on 2018-09-02 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180902_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 18, 36, 44, 816097), verbose_name='添加时间'),
        ),
    ]
