# Generated by Django 2.1 on 2018-09-02 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180902_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 21, 30, 17, 408026), verbose_name='添加时间'),
        ),
    ]
