# Generated by Django 2.1 on 2018-09-02 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20180902_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 21, 37, 53, 526359), verbose_name='添加时间'),
        ),
    ]
