# Generated by Django 2.1.1 on 2018-09-06 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180902_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 14, 51, 2, 227217), verbose_name='添加时间'),
        ),
    ]
