# Generated by Django 2.1.1 on 2018-09-06 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20180906_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 19, 58, 3, 748071), verbose_name='添加时间'),
        ),
    ]
