# Generated by Django 2.1 on 2018-09-06 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20180906_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 21, 12, 1, 710010), verbose_name='添加时间'),
        ),
    ]
