# Generated by Django 2.1.1 on 2018-09-06 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_auto_20180906_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 19, 58, 3, 761913), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 19, 58, 3, 760820), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_FINISHED', '交易完成'), ('TRADE_SUCCESS', '支付成功'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '交易关闭')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 19, 58, 3, 759642), verbose_name='添加时间'),
        ),
    ]
